//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Id { get; set; }
        public string AccountName { get; set; }
        public int AccountNo { get; set; }
        public int Balance { get; set; }
        public int Interest { get; set; }
        public int EarlyPaymentFee { get; set; }
        public int Carryover { get; set; }
    }
}
